### ISSUE TITLE
Add next/previous

### ISSUE THREAD

**Issue by maaraneasi** [Skipstone/Skipstone#16]
Please implement ability to control next/previous - the rewind is nice but not very useful...
Thanks!

**Comment by petehare** [comment]
@Neal I could make another "page" for the next/prev, but just not sure it 4 screens is getting too much. Thoughts?

**Comment by Neal** [comment]
4 screens may be too much, but I’d rather prefer to have more functionality.

Although being able to fully customize number of screens and what each button does in each screen would be dope.


On January 3, 2015 at 23:26:17, Pete Hare (notifications@github.com) wrote:

@Neal I could make another "page" for the next/prev, but just not sure it 4 screens is getting too much. Thoughts?
