### ISSUE TITLE
Unable to remove Media Player from configuration

### ISSUE THREAD

**Issue by xbgmsharp** [Skipstone/Skipstone#22]
On the configuration web page, I found out that there is no way to delete a Media Player.
I was able to add my 2 Media Player but I added one more (by miss take, did't see it) and now I can't delete it. Now on the watch, I have 3 entries but only 2 valid.
I suggest any empty "Friendly Name" alias "title" could be skip.

**Comment by spangborn** [comment]
Swipe on the title of the player and it'll display a delete icon.

**Comment by xbgmsharp** [comment]
Thanks
